<?php

/**
 *
 *
 *
 *
 */
function form_question_permission() {
	return array(
		'submit form_question' => array(
			'title' => t('Submit form_question'),
			'description' => t('Submit the form_question form'),
			),
		'access form_question submissions' => array(
			'title' => t('Access form_question submissions'),
			'description' => t('Access the form_question submissions'),
			),
		);
}

function form_question_menu() {
  $items = array();
  $items['form-question'] = array(
    'title' => 'Question Upload',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('submit form_question'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_question_form'),
  );
  $items['form-submissions'] = array(
    'title' => 'Question Submissions',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access form_question submissions'),
    'page callback' => 'form_question_submissions',
  );

  return $items;
}

function get_subjects() {
	$results = db_query("SELECT * FROM {node}");
	$subjects = array();
	if (!empty($results)) {
		$subjects[] = t('');
		foreach($results AS $result) {
			if (!in_array(ucwords(strtolower(t($result->title))),$subjects)) {
				$subjects[] = ucwords(strtolower(t($result->title)));
			}	
		}
		sort($subjects);
	}
	return $subjects;
}

function form_question_form($form, &$form_state) {
	$form['select_subject'] = array(
		'#type' => 'select',
		'#title' => t('Select a Subject'),
		'#options' => get_subjects(),
		'#description' => t('A subject must be selected here or input below. Please only use one.')
		);

	$form['subject'] = array(
		'#type' => 'textfield',
		'#title' => t('Subject'),
		'#size' => 30,
		'#maxlength' => 40,
		'#required' => FALSE,
		'#description' => t('Only use if your subject is not in the selection above.'),
		);

	$form['tags'] = array(
		'#type' => 'textfield',
		'#title' => t('Tags'),
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => FALSE,
		'#description' => t('Input tags that can be used to find this question.'),
		);

	$form['question'] = array(
		'#title' => t('Math Question'),
		'#type' => 'textarea',
		'#description' => t('Input math question or upload file below.'),
		'#default_value' => '',
		'#required' => FALSE,
		);

	$form['file_upload'] = array(
		'#title' => t('Upload File'),
		'#type' => 'managed_file',
		);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Add item'),
		);

	return $form;
}

function form_question_form_validate($form, &$form_state) {
	$valid = TRUE;
	if (($form_state['values']['select_subject'] == 0) && (empty($form_state['values']['subject']))) {
		form_set_error('subject', t('You must select or enter a subject'));
  	$valid = FALSE;
  }
  if (empty($form_state['values']['question']) && (empty($form_state['values']['file_upload']))) {
  	form_set_error('question', t('You must enter or upload a question'));
  	$valid = FALSE;
	}
	return $valid;
}

function form_question_form_submit($form, &$form_state) {
  $body_text = $form_state['values']['question'];
  $node = new stdClass();
  $node->type = 'article';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;

  if (!empty($form_state['values']['subject'])) {
  	$node->title = ucwords(strtolower($form_state['values']['subject']));
  } else {
  	$node->title = get_subjects()[$form_state['values']['select_subject']];
  }

  if (!empty($form_state['values']['tags'])) {
 	  $new_term = array(
 	    'vid' => 1,
  	  'name' => $form_state['values']['tags'],
		);
		$new_term = (object) $new_term;
		taxonomy_term_save($new_term);

  	$node->field_tags[$node->language][0]['tid'] = $new_term->tid;
	}

  $node->body[$node->language][0]['value']   = $body_text;
  $node->body[$node->language][0]['summary'] = text_summary($body_text);
  $node->body[$node->language][0]['format']  = 'filtered_html';
    
  $path = 'content/' .$form_state['values']['subject'] . date('YmdHis');
  $node->path = array('alias' => $path);

  if (!empty($form_state['values']['file_upload'])) {
  	$filepath = drupal_realpath($form_state['values']['file_upload']);
    $file = file_load($form_state['values']['file_upload']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $node->field_image[LANGUAGE_NONE][0] = (array)$file;
  }
  $title = $node->title;
  $node->field_search_title[LANGUAGE_NONE][0]['value'] = $title;
  node_save($node);

 	drupal_set_message(t("Your form entry has been added with a subject of '@subject', 
 		tags of '@tags', and with the question as '@question'.", array(
		'@subject' => $title,
		'@tags' => $form_state['values']['tags'],
		'@question' => $form_state['values']['question'],
	)));
}

function form_question_submissions() {
	$results = db_query("SELECT * FROM {form_question}");

	$header = array(t('Subject'), t('Tags'), t('Question'));
	$rows = array();

	foreach($results AS $result) {
		$rows[] = array(
			$result->subject,
			$result->tags,
			$result->question,
		);
	}

  $build = array();
  $build['table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );
  $build['pager'] = array(
    '#theme' => 'pager',
  );
  return $build;
}