<?php

/**
 * @file
 * myblock.module
 */

function myblock_block_info() {
  $blocks['myblock'] = array(
    'info' => t('My Custom Block'),
  );

  return $blocks;
}

function myblock_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'myblock':
      $block['subject'] = t('This is my Custom Block');
      $block['content'] = "<h1>Hello</h1> This is my block";
      break;
  }
  return $block;
}