<?php

/**
 * Implements hook_permission().
 */
function form_example_permission() {
	return array(
		'submit form_example' => array(
			'title' => t('Submit form_example'),
			'description' => t('Submit the form_example form'),
			),
		);
}

function form_example_menu() {
  $items = array();
  $items['form-example'] = array(
    'title' => 'My Example Form',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('submit form_example'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_example_form')
  );

  return $items;
}

function form_example_form($form, &$form_state) {
	$form['mynumber'] = array(
		'#type' => 'textfield',
		'#title' => t('My number'),
		'#size' => 10,
		'#maxlength' => 10,
		'#required' => TRUE,
		'#description' => t('Please enter a valid number'),
		);

	$form['mytextfield'] = array(
		'#type' => 'textfield',
		'#title' => t('My Textfield'),
		'#size' => 60,
		'#maxlength' => 128,
		'#required' => TRUE,
		);

	$form['mytext'] = array(
		'#title' => t('My Textarea'),
		'#type' => 'textarea',
		'#description' => t('Enter some text.'),
		'#default_value' => '',
		'#required' => TRUE,
		);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Add item'),
		);

	return $form;
}

function form_example_form_validate($form, &$form_state) {
	//print('<pre>'.print_r($form_state['values'],1).'</pre>');die();
	if (!is_numeric($form_state['values']['mynumber'])) {
		form_set_error('mynumber', t('You must enter a valid number'));
		return FALSE;
	}
	return TRUE;
}

function form_example_form_submit($form, &$form_state) {
	$fe_id = db_insert('form_example')
		->fields(array(
			'mynumber' => $form_state['values']['mynumber'],
			'mytextfield' => $form_state['values']['mytextfield'],
			'mytext' => $form_state['values']['mytext'],
		))
		->execute();

	drupal_set_message(t("Your form entry has been added."));
}

